name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master! and test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t milkomilchev/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true milkomilchev/react-test npm test

      - run: docker build -t milkomilchev/multi-client ./client
      - run: docker build -t milkomilchev/multi-nginx ./nginx
      - run: docker build -t milkomilchev/multi-server ./server
      - run: docker build -t milkomilchev/multi-worker ./worker

      - run: docker push milkomilchev/multi-client
      - run: docker push milkomilchev/multi-nginx
      - run: docker push milkomilchev/multi-server
      - run: docker push milkomilchev/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: milkomilchev/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-eu-central-1-821327299525
          region: eu-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
